-- 5-Point Likert Options & Scoring Rules Seed Migration

INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_1_1', 'q_att_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_1_2', 'q_att_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_1_3', 'q_att_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_1_4', 'q_att_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_1_5', 'q_att_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_2_1', 'q_att_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_2_2', 'q_att_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_2_3', 'q_att_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_2_4', 'q_att_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_2_5', 'q_att_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_3_1', 'q_att_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_3_2', 'q_att_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_3_3', 'q_att_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_3_4', 'q_att_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_3_5', 'q_att_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_4_1', 'q_att_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_4_2', 'q_att_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_4_3', 'q_att_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_4_4', 'q_att_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_4_5', 'q_att_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_5_1', 'q_att_5', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_5_2', 'q_att_5', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_5_3', 'q_att_5', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_5_4', 'q_att_5', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_5_5', 'q_att_5', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_6_1', 'q_att_6', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_6_2', 'q_att_6', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_6_3', 'q_att_6', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_6_4', 'q_att_6', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_6_5', 'q_att_6', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_7_1', 'q_att_7', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_7_2', 'q_att_7', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_7_3', 'q_att_7', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_7_4', 'q_att_7', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_7_5', 'q_att_7', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_8_1', 'q_att_8', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_8_2', 'q_att_8', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_8_3', 'q_att_8', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_8_4', 'q_att_8', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_att_8_5', 'q_att_8', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_1_1', 'q_ll_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_1_2', 'q_ll_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_1_3', 'q_ll_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_1_4', 'q_ll_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_1_5', 'q_ll_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_2_1', 'q_ll_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_2_2', 'q_ll_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_2_3', 'q_ll_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_2_4', 'q_ll_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_2_5', 'q_ll_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_3_1', 'q_ll_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_3_2', 'q_ll_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_3_3', 'q_ll_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_3_4', 'q_ll_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_3_5', 'q_ll_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_4_1', 'q_ll_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_4_2', 'q_ll_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_4_3', 'q_ll_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_4_4', 'q_ll_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_4_5', 'q_ll_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_5_1', 'q_ll_5', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_5_2', 'q_ll_5', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_5_3', 'q_ll_5', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_5_4', 'q_ll_5', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ll_5_5', 'q_ll_5', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_1_1', 'q_eq_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_1_2', 'q_eq_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_1_3', 'q_eq_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_1_4', 'q_eq_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_1_5', 'q_eq_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_2_1', 'q_eq_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_2_2', 'q_eq_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_2_3', 'q_eq_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_2_4', 'q_eq_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_2_5', 'q_eq_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_3_1', 'q_eq_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_3_2', 'q_eq_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_3_3', 'q_eq_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_3_4', 'q_eq_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_3_5', 'q_eq_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_4_1', 'q_eq_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_4_2', 'q_eq_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_4_3', 'q_eq_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_4_4', 'q_eq_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_4_5', 'q_eq_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_5_1', 'q_eq_5', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_5_2', 'q_eq_5', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_5_3', 'q_eq_5', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_5_4', 'q_eq_5', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_eq_5_5', 'q_eq_5', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_1_1', 'q_ie_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_1_2', 'q_ie_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_1_3', 'q_ie_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_1_4', 'q_ie_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_1_5', 'q_ie_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_2_1', 'q_ie_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_2_2', 'q_ie_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_2_3', 'q_ie_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_2_4', 'q_ie_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_2_5', 'q_ie_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_3_1', 'q_ie_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_3_2', 'q_ie_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_3_3', 'q_ie_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_3_4', 'q_ie_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_3_5', 'q_ie_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_4_1', 'q_ie_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_4_2', 'q_ie_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_4_3', 'q_ie_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_4_4', 'q_ie_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_ie_4_5', 'q_ie_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_1_1', 'q_se_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_1_2', 'q_se_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_1_3', 'q_se_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_1_4', 'q_se_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_1_5', 'q_se_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_2_1', 'q_se_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_2_2', 'q_se_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_2_3', 'q_se_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_2_4', 'q_se_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_2_5', 'q_se_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_3_1', 'q_se_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_3_2', 'q_se_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_3_3', 'q_se_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_3_4', 'q_se_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_3_5', 'q_se_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_4_1', 'q_se_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_4_2', 'q_se_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_4_3', 'q_se_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_4_4', 'q_se_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_se_4_5', 'q_se_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_1_1', 'q_cs_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_1_2', 'q_cs_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_1_3', 'q_cs_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_1_4', 'q_cs_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_1_5', 'q_cs_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_2_1', 'q_cs_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_2_2', 'q_cs_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_2_3', 'q_cs_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_2_4', 'q_cs_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_2_5', 'q_cs_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_3_1', 'q_cs_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_3_2', 'q_cs_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_3_3', 'q_cs_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_3_4', 'q_cs_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_3_5', 'q_cs_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_4_1', 'q_cs_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_4_2', 'q_cs_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_4_3', 'q_cs_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_4_4', 'q_cs_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cs_4_5', 'q_cs_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_1_1', 'q_cf_1', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_1_2', 'q_cf_1', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_1_3', 'q_cf_1', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_1_4', 'q_cf_1', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_1_5', 'q_cf_1', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_2_1', 'q_cf_2', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_2_2', 'q_cf_2', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_2_3', 'q_cf_2', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_2_4', 'q_cf_2', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_2_5', 'q_cf_2', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_3_1', 'q_cf_3', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_3_2', 'q_cf_3', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_3_3', 'q_cf_3', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_3_4', 'q_cf_3', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_3_5', 'q_cf_3', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_4_1', 'q_cf_4', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_4_2', 'q_cf_4', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_4_3', 'q_cf_4', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_4_4', 'q_cf_4', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_4_5', 'q_cf_4', 'Strongly Agree', '5', 5, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_5_1', 'q_cf_5', 'Strongly Disagree', '1', 1, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_5_2', 'q_cf_5', 'Disagree', '2', 2, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_5_3', 'q_cf_5', 'Neutral', '3', 3, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_5_4', 'q_cf_5', 'Agree', '4', 4, 'active');
INSERT OR REPLACE INTO question_options (id, question_id, option_text, option_value, display_order, status) VALUES ('opt_q_cf_5_5', 'q_cf_5', 'Strongly Agree', '5', 5, 'active');

-- Scoring Rules
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_1_1', 'asm_attachment', 'q_att_1', 'dim_att_secure', 'opt_q_att_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_1_2', 'asm_attachment', 'q_att_1', 'dim_att_secure', 'opt_q_att_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_1_3', 'asm_attachment', 'q_att_1', 'dim_att_secure', 'opt_q_att_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_1_4', 'asm_attachment', 'q_att_1', 'dim_att_secure', 'opt_q_att_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_1_5', 'asm_attachment', 'q_att_1', 'dim_att_secure', 'opt_q_att_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_2_1', 'asm_attachment', 'q_att_2', 'dim_att_secure', 'opt_q_att_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_2_2', 'asm_attachment', 'q_att_2', 'dim_att_secure', 'opt_q_att_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_2_3', 'asm_attachment', 'q_att_2', 'dim_att_secure', 'opt_q_att_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_2_4', 'asm_attachment', 'q_att_2', 'dim_att_secure', 'opt_q_att_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_2_5', 'asm_attachment', 'q_att_2', 'dim_att_secure', 'opt_q_att_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_3_1', 'asm_attachment', 'q_att_3', 'dim_att_anxious', 'opt_q_att_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_3_2', 'asm_attachment', 'q_att_3', 'dim_att_anxious', 'opt_q_att_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_3_3', 'asm_attachment', 'q_att_3', 'dim_att_anxious', 'opt_q_att_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_3_4', 'asm_attachment', 'q_att_3', 'dim_att_anxious', 'opt_q_att_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_3_5', 'asm_attachment', 'q_att_3', 'dim_att_anxious', 'opt_q_att_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_4_1', 'asm_attachment', 'q_att_4', 'dim_att_anxious', 'opt_q_att_4_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_4_2', 'asm_attachment', 'q_att_4', 'dim_att_anxious', 'opt_q_att_4_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_4_3', 'asm_attachment', 'q_att_4', 'dim_att_anxious', 'opt_q_att_4_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_4_4', 'asm_attachment', 'q_att_4', 'dim_att_anxious', 'opt_q_att_4_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_4_5', 'asm_attachment', 'q_att_4', 'dim_att_anxious', 'opt_q_att_4_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_5_1', 'asm_attachment', 'q_att_5', 'dim_att_avoidant', 'opt_q_att_5_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_5_2', 'asm_attachment', 'q_att_5', 'dim_att_avoidant', 'opt_q_att_5_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_5_3', 'asm_attachment', 'q_att_5', 'dim_att_avoidant', 'opt_q_att_5_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_5_4', 'asm_attachment', 'q_att_5', 'dim_att_avoidant', 'opt_q_att_5_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_5_5', 'asm_attachment', 'q_att_5', 'dim_att_avoidant', 'opt_q_att_5_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_6_1', 'asm_attachment', 'q_att_6', 'dim_att_avoidant', 'opt_q_att_6_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_6_2', 'asm_attachment', 'q_att_6', 'dim_att_avoidant', 'opt_q_att_6_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_6_3', 'asm_attachment', 'q_att_6', 'dim_att_avoidant', 'opt_q_att_6_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_6_4', 'asm_attachment', 'q_att_6', 'dim_att_avoidant', 'opt_q_att_6_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_6_5', 'asm_attachment', 'q_att_6', 'dim_att_avoidant', 'opt_q_att_6_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_7_1', 'asm_attachment', 'q_att_7', 'dim_att_fearful', 'opt_q_att_7_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_7_2', 'asm_attachment', 'q_att_7', 'dim_att_fearful', 'opt_q_att_7_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_7_3', 'asm_attachment', 'q_att_7', 'dim_att_fearful', 'opt_q_att_7_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_7_4', 'asm_attachment', 'q_att_7', 'dim_att_fearful', 'opt_q_att_7_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_7_5', 'asm_attachment', 'q_att_7', 'dim_att_fearful', 'opt_q_att_7_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_8_1', 'asm_attachment', 'q_att_8', 'dim_att_fearful', 'opt_q_att_8_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_8_2', 'asm_attachment', 'q_att_8', 'dim_att_fearful', 'opt_q_att_8_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_8_3', 'asm_attachment', 'q_att_8', 'dim_att_fearful', 'opt_q_att_8_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_8_4', 'asm_attachment', 'q_att_8', 'dim_att_fearful', 'opt_q_att_8_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_att_8_5', 'asm_attachment', 'q_att_8', 'dim_att_fearful', 'opt_q_att_8_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_1_1', 'asm_love_language', 'q_ll_1', 'dim_ll_words', 'opt_q_ll_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_1_2', 'asm_love_language', 'q_ll_1', 'dim_ll_words', 'opt_q_ll_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_1_3', 'asm_love_language', 'q_ll_1', 'dim_ll_words', 'opt_q_ll_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_1_4', 'asm_love_language', 'q_ll_1', 'dim_ll_words', 'opt_q_ll_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_1_5', 'asm_love_language', 'q_ll_1', 'dim_ll_words', 'opt_q_ll_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_2_1', 'asm_love_language', 'q_ll_2', 'dim_ll_time', 'opt_q_ll_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_2_2', 'asm_love_language', 'q_ll_2', 'dim_ll_time', 'opt_q_ll_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_2_3', 'asm_love_language', 'q_ll_2', 'dim_ll_time', 'opt_q_ll_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_2_4', 'asm_love_language', 'q_ll_2', 'dim_ll_time', 'opt_q_ll_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_2_5', 'asm_love_language', 'q_ll_2', 'dim_ll_time', 'opt_q_ll_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_3_1', 'asm_love_language', 'q_ll_3', 'dim_ll_gifts', 'opt_q_ll_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_3_2', 'asm_love_language', 'q_ll_3', 'dim_ll_gifts', 'opt_q_ll_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_3_3', 'asm_love_language', 'q_ll_3', 'dim_ll_gifts', 'opt_q_ll_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_3_4', 'asm_love_language', 'q_ll_3', 'dim_ll_gifts', 'opt_q_ll_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_3_5', 'asm_love_language', 'q_ll_3', 'dim_ll_gifts', 'opt_q_ll_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_4_1', 'asm_love_language', 'q_ll_4', 'dim_ll_acts', 'opt_q_ll_4_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_4_2', 'asm_love_language', 'q_ll_4', 'dim_ll_acts', 'opt_q_ll_4_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_4_3', 'asm_love_language', 'q_ll_4', 'dim_ll_acts', 'opt_q_ll_4_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_4_4', 'asm_love_language', 'q_ll_4', 'dim_ll_acts', 'opt_q_ll_4_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_4_5', 'asm_love_language', 'q_ll_4', 'dim_ll_acts', 'opt_q_ll_4_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_5_1', 'asm_love_language', 'q_ll_5', 'dim_ll_touch', 'opt_q_ll_5_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_5_2', 'asm_love_language', 'q_ll_5', 'dim_ll_touch', 'opt_q_ll_5_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_5_3', 'asm_love_language', 'q_ll_5', 'dim_ll_touch', 'opt_q_ll_5_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_5_4', 'asm_love_language', 'q_ll_5', 'dim_ll_touch', 'opt_q_ll_5_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ll_5_5', 'asm_love_language', 'q_ll_5', 'dim_ll_touch', 'opt_q_ll_5_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_1_1', 'asm_eq', 'q_eq_1', 'dim_eq_aware', 'opt_q_eq_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_1_2', 'asm_eq', 'q_eq_1', 'dim_eq_aware', 'opt_q_eq_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_1_3', 'asm_eq', 'q_eq_1', 'dim_eq_aware', 'opt_q_eq_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_1_4', 'asm_eq', 'q_eq_1', 'dim_eq_aware', 'opt_q_eq_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_1_5', 'asm_eq', 'q_eq_1', 'dim_eq_aware', 'opt_q_eq_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_2_1', 'asm_eq', 'q_eq_2', 'dim_eq_reg', 'opt_q_eq_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_2_2', 'asm_eq', 'q_eq_2', 'dim_eq_reg', 'opt_q_eq_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_2_3', 'asm_eq', 'q_eq_2', 'dim_eq_reg', 'opt_q_eq_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_2_4', 'asm_eq', 'q_eq_2', 'dim_eq_reg', 'opt_q_eq_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_2_5', 'asm_eq', 'q_eq_2', 'dim_eq_reg', 'opt_q_eq_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_3_1', 'asm_eq', 'q_eq_3', 'dim_eq_mot', 'opt_q_eq_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_3_2', 'asm_eq', 'q_eq_3', 'dim_eq_mot', 'opt_q_eq_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_3_3', 'asm_eq', 'q_eq_3', 'dim_eq_mot', 'opt_q_eq_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_3_4', 'asm_eq', 'q_eq_3', 'dim_eq_mot', 'opt_q_eq_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_3_5', 'asm_eq', 'q_eq_3', 'dim_eq_mot', 'opt_q_eq_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_4_1', 'asm_eq', 'q_eq_4', 'dim_eq_emp', 'opt_q_eq_4_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_4_2', 'asm_eq', 'q_eq_4', 'dim_eq_emp', 'opt_q_eq_4_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_4_3', 'asm_eq', 'q_eq_4', 'dim_eq_emp', 'opt_q_eq_4_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_4_4', 'asm_eq', 'q_eq_4', 'dim_eq_emp', 'opt_q_eq_4_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_4_5', 'asm_eq', 'q_eq_4', 'dim_eq_emp', 'opt_q_eq_4_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_5_1', 'asm_eq', 'q_eq_5', 'dim_eq_soc', 'opt_q_eq_5_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_5_2', 'asm_eq', 'q_eq_5', 'dim_eq_soc', 'opt_q_eq_5_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_5_3', 'asm_eq', 'q_eq_5', 'dim_eq_soc', 'opt_q_eq_5_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_5_4', 'asm_eq', 'q_eq_5', 'dim_eq_soc', 'opt_q_eq_5_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_eq_5_5', 'asm_eq', 'q_eq_5', 'dim_eq_soc', 'opt_q_eq_5_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_1_1', 'asm_intro_extro', 'q_ie_1', 'dim_ie_intro', 'opt_q_ie_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_1_2', 'asm_intro_extro', 'q_ie_1', 'dim_ie_intro', 'opt_q_ie_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_1_3', 'asm_intro_extro', 'q_ie_1', 'dim_ie_intro', 'opt_q_ie_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_1_4', 'asm_intro_extro', 'q_ie_1', 'dim_ie_intro', 'opt_q_ie_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_1_5', 'asm_intro_extro', 'q_ie_1', 'dim_ie_intro', 'opt_q_ie_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_2_1', 'asm_intro_extro', 'q_ie_2', 'dim_ie_intro', 'opt_q_ie_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_2_2', 'asm_intro_extro', 'q_ie_2', 'dim_ie_intro', 'opt_q_ie_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_2_3', 'asm_intro_extro', 'q_ie_2', 'dim_ie_intro', 'opt_q_ie_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_2_4', 'asm_intro_extro', 'q_ie_2', 'dim_ie_intro', 'opt_q_ie_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_2_5', 'asm_intro_extro', 'q_ie_2', 'dim_ie_intro', 'opt_q_ie_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_3_1', 'asm_intro_extro', 'q_ie_3', 'dim_ie_extro', 'opt_q_ie_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_3_2', 'asm_intro_extro', 'q_ie_3', 'dim_ie_extro', 'opt_q_ie_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_3_3', 'asm_intro_extro', 'q_ie_3', 'dim_ie_extro', 'opt_q_ie_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_3_4', 'asm_intro_extro', 'q_ie_3', 'dim_ie_extro', 'opt_q_ie_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_3_5', 'asm_intro_extro', 'q_ie_3', 'dim_ie_extro', 'opt_q_ie_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_4_1', 'asm_intro_extro', 'q_ie_4', 'dim_ie_extro', 'opt_q_ie_4_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_4_2', 'asm_intro_extro', 'q_ie_4', 'dim_ie_extro', 'opt_q_ie_4_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_4_3', 'asm_intro_extro', 'q_ie_4', 'dim_ie_extro', 'opt_q_ie_4_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_4_4', 'asm_intro_extro', 'q_ie_4', 'dim_ie_extro', 'opt_q_ie_4_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_ie_4_5', 'asm_intro_extro', 'q_ie_4', 'dim_ie_extro', 'opt_q_ie_4_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_1_1', 'asm_self_esteem', 'q_se_1', 'dim_se_worth', 'opt_q_se_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_1_2', 'asm_self_esteem', 'q_se_1', 'dim_se_worth', 'opt_q_se_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_1_3', 'asm_self_esteem', 'q_se_1', 'dim_se_worth', 'opt_q_se_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_1_4', 'asm_self_esteem', 'q_se_1', 'dim_se_worth', 'opt_q_se_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_1_5', 'asm_self_esteem', 'q_se_1', 'dim_se_worth', 'opt_q_se_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_2_1', 'asm_self_esteem', 'q_se_2', 'dim_se_worth', 'opt_q_se_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_2_2', 'asm_self_esteem', 'q_se_2', 'dim_se_worth', 'opt_q_se_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_2_3', 'asm_self_esteem', 'q_se_2', 'dim_se_worth', 'opt_q_se_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_2_4', 'asm_self_esteem', 'q_se_2', 'dim_se_worth', 'opt_q_se_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_2_5', 'asm_self_esteem', 'q_se_2', 'dim_se_worth', 'opt_q_se_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_3_1', 'asm_self_esteem', 'q_se_3', 'dim_se_eff', 'opt_q_se_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_3_2', 'asm_self_esteem', 'q_se_3', 'dim_se_eff', 'opt_q_se_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_3_3', 'asm_self_esteem', 'q_se_3', 'dim_se_eff', 'opt_q_se_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_3_4', 'asm_self_esteem', 'q_se_3', 'dim_se_eff', 'opt_q_se_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_3_5', 'asm_self_esteem', 'q_se_3', 'dim_se_eff', 'opt_q_se_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_4_1', 'asm_self_esteem', 'q_se_4', 'dim_se_worth', 'opt_q_se_4_1', 5.0, 1.0, 1);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_4_2', 'asm_self_esteem', 'q_se_4', 'dim_se_worth', 'opt_q_se_4_2', 4.0, 1.0, 1);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_4_3', 'asm_self_esteem', 'q_se_4', 'dim_se_worth', 'opt_q_se_4_3', 3.0, 1.0, 1);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_4_4', 'asm_self_esteem', 'q_se_4', 'dim_se_worth', 'opt_q_se_4_4', 2.0, 1.0, 1);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_se_4_5', 'asm_self_esteem', 'q_se_4', 'dim_se_worth', 'opt_q_se_4_5', 1.0, 1.0, 1);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_1_1', 'asm_communication', 'q_cs_1', 'dim_cs_assert', 'opt_q_cs_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_1_2', 'asm_communication', 'q_cs_1', 'dim_cs_assert', 'opt_q_cs_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_1_3', 'asm_communication', 'q_cs_1', 'dim_cs_assert', 'opt_q_cs_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_1_4', 'asm_communication', 'q_cs_1', 'dim_cs_assert', 'opt_q_cs_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_1_5', 'asm_communication', 'q_cs_1', 'dim_cs_assert', 'opt_q_cs_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_2_1', 'asm_communication', 'q_cs_2', 'dim_cs_pass', 'opt_q_cs_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_2_2', 'asm_communication', 'q_cs_2', 'dim_cs_pass', 'opt_q_cs_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_2_3', 'asm_communication', 'q_cs_2', 'dim_cs_pass', 'opt_q_cs_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_2_4', 'asm_communication', 'q_cs_2', 'dim_cs_pass', 'opt_q_cs_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_2_5', 'asm_communication', 'q_cs_2', 'dim_cs_pass', 'opt_q_cs_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_3_1', 'asm_communication', 'q_cs_3', 'dim_cs_aggr', 'opt_q_cs_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_3_2', 'asm_communication', 'q_cs_3', 'dim_cs_aggr', 'opt_q_cs_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_3_3', 'asm_communication', 'q_cs_3', 'dim_cs_aggr', 'opt_q_cs_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_3_4', 'asm_communication', 'q_cs_3', 'dim_cs_aggr', 'opt_q_cs_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_3_5', 'asm_communication', 'q_cs_3', 'dim_cs_aggr', 'opt_q_cs_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_4_1', 'asm_communication', 'q_cs_4', 'dim_cs_pass_aggr', 'opt_q_cs_4_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_4_2', 'asm_communication', 'q_cs_4', 'dim_cs_pass_aggr', 'opt_q_cs_4_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_4_3', 'asm_communication', 'q_cs_4', 'dim_cs_pass_aggr', 'opt_q_cs_4_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_4_4', 'asm_communication', 'q_cs_4', 'dim_cs_pass_aggr', 'opt_q_cs_4_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cs_4_5', 'asm_communication', 'q_cs_4', 'dim_cs_pass_aggr', 'opt_q_cs_4_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_1_1', 'asm_conflict', 'q_cf_1', 'dim_cf_collab', 'opt_q_cf_1_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_1_2', 'asm_conflict', 'q_cf_1', 'dim_cf_collab', 'opt_q_cf_1_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_1_3', 'asm_conflict', 'q_cf_1', 'dim_cf_collab', 'opt_q_cf_1_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_1_4', 'asm_conflict', 'q_cf_1', 'dim_cf_collab', 'opt_q_cf_1_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_1_5', 'asm_conflict', 'q_cf_1', 'dim_cf_collab', 'opt_q_cf_1_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_2_1', 'asm_conflict', 'q_cf_2', 'dim_cf_comp', 'opt_q_cf_2_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_2_2', 'asm_conflict', 'q_cf_2', 'dim_cf_comp', 'opt_q_cf_2_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_2_3', 'asm_conflict', 'q_cf_2', 'dim_cf_comp', 'opt_q_cf_2_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_2_4', 'asm_conflict', 'q_cf_2', 'dim_cf_comp', 'opt_q_cf_2_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_2_5', 'asm_conflict', 'q_cf_2', 'dim_cf_comp', 'opt_q_cf_2_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_3_1', 'asm_conflict', 'q_cf_3', 'dim_cf_accom', 'opt_q_cf_3_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_3_2', 'asm_conflict', 'q_cf_3', 'dim_cf_accom', 'opt_q_cf_3_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_3_3', 'asm_conflict', 'q_cf_3', 'dim_cf_accom', 'opt_q_cf_3_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_3_4', 'asm_conflict', 'q_cf_3', 'dim_cf_accom', 'opt_q_cf_3_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_3_5', 'asm_conflict', 'q_cf_3', 'dim_cf_accom', 'opt_q_cf_3_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_4_1', 'asm_conflict', 'q_cf_4', 'dim_cf_compete', 'opt_q_cf_4_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_4_2', 'asm_conflict', 'q_cf_4', 'dim_cf_compete', 'opt_q_cf_4_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_4_3', 'asm_conflict', 'q_cf_4', 'dim_cf_compete', 'opt_q_cf_4_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_4_4', 'asm_conflict', 'q_cf_4', 'dim_cf_compete', 'opt_q_cf_4_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_4_5', 'asm_conflict', 'q_cf_4', 'dim_cf_compete', 'opt_q_cf_4_5', 5.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_5_1', 'asm_conflict', 'q_cf_5', 'dim_cf_avoid', 'opt_q_cf_5_1', 1.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_5_2', 'asm_conflict', 'q_cf_5', 'dim_cf_avoid', 'opt_q_cf_5_2', 2.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_5_3', 'asm_conflict', 'q_cf_5', 'dim_cf_avoid', 'opt_q_cf_5_3', 3.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_5_4', 'asm_conflict', 'q_cf_5', 'dim_cf_avoid', 'opt_q_cf_5_4', 4.0, 1.0, 0);
INSERT OR REPLACE INTO scoring_rules (id, assessment_id, question_id, dimension_id, option_id, score, weight, reverse_scoring) VALUES ('sr_q_cf_5_5', 'asm_conflict', 'q_cf_5', 'dim_cf_avoid', 'opt_q_cf_5_5', 5.0, 1.0, 0);
